export { default as trademark } from './product/trademark'
export { default as category } from './product/category'
export { default as table } from './table'
export { default as sku } from './product/sku'
export { default as spu } from './product/spu'